pelican:
  notify:         users@infra.apache.org
  autobuild:      true
  target:         asf-site
  
staging: false


github:
  description:   Infrastructure Website
  ghp_branch:    master
  ghp_path:      /docs
