pelican:
  notify:         private@infra.apache.org
  autobuild:      true
  target:         asf-site
  whoami:         master
  
staging:
  whoami: asf-break-test


github:
  ghp_branch:    master
  ghp_path:      /docs

jenkins:
  github_whitelist:
    - KibbleDemo
