pelican:
  notify:         private@infra.apache.org
  autobuild:      true
  target:         asf-site
  
staging:
  whoami: asf-break-test

custombuild:
  whoami: custombuild
  target: customtarget
  outputdir: output
  buildscript: "bash -c /tmp/source/pelican_build.sh"

staging:
  whoami: customtarget
  profile: custom

github:
  ghp_branch:    master
  ghp_path:      /docs

jenkins:
  github_whitelist:
    - KibbleDemo
