pelican:
  notify:         private@infra.apache.org
  autobuild:      true
  target:         asf-site

pelican:
  whoami: pelican-test
  target: asf-break-test

staging: false


github:
  ghp_branch:    master
  ghp_path:      /docs

jenkins:
  github_whitelist:
    - KibbleDemo
