pelican:
  notify:         private@infra.apache.org
  autobuild:      true
  target:         asf-site
  whoami:         master
  
staging:
  whoami: asf-break-test
  profile: ~

pelican:
  notify:         private@infra.apache.org
  autobuild:      true
  target:         asf-staging-nopages
  whoami:         nopages-test
  
staging:
  whoami: asf-staging-nopages
  profile: beta


github:
  ghp_branch:    master
  ghp_path:      /docs

jenkins:
  github_whitelist:
    - KibbleDemo
