pelican:
  notify:         notifications@infra.apache.org
  autobuild:      true
  target:         asf-site
  whoami:         master
  
staging:
  whoami: asf-break-test
  profile: ~

github:
  ghp_branch:    master
  ghp_path:      /docs

jenkins:
  github_whitelist:
    - KibbleDemo

notifications:
  commits:              commits@infra.apache.org
  pullrequests_status:  users@infra.apache.org
  pullrequests_comment: commits@infra.apache.org
  issues:               users@infra.apache.org
